[package]
name = "slipstream"
version = "0.1.0"
edition = "2021"
authors = ["Trark"]

[dependencies]
docopt = "1.1.1"
serde = "1.0.130"

[dependencies.slp_sequence_hlsl_to_cl]
path = "../src/sequence/hlsl_to_cl"
