[package]
name = "slp_transform_lexer"
version = "0.1.0"
authors = ["Trark"]

[dependencies]
nom = "1.0.0"

[dependencies.slp_shared]
path = "../../shared"

[dependencies.slp_lang_htk]
path = "../../lang/htk"

[dependencies.slp_transform_preprocess]
path = "../preprocess"
