[package]
name = "slp_transform_cst_printer"
version = "0.1.0"
edition = "2021"
authors = ["Trark"]

[dependencies.slp_shared]
path = "../../shared"

[dependencies.slp_lang_cst]
path = "../../lang/cst"
